SGPS/SGPS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sgpsociais.urls')),
]

SGPS/sgpsociais/urls.py
from django.urls import path
from .views import *

app_name = 'sgps'

urlpatterns = [
    path('', logon, name='logon'),
    path('logoff/', logoff, name='logoff'),
    path('home/', home, name='home'),
    path('cadastro_jovem/', cadastro_jovem, name='cadastro_jovem'),
    path('cadastro_crianca/', cadastro_crianca, name='cadastro_crianca'),
    path('cadastro_idoso/', cadastro_idoso, name='cadastro_idoso'),
    path('listar_jovem/', listar_jovem, name='listar_jovem'),
    path('listar_crianca/', listar_crianca, name='listar_crianca'),
    path('listar_idoso/', listar_idoso, name='listar_idoso'),
    path('suporte/', suporte, name='suporte'),
    path('preferencias/', preferencias, name='preferencias'),
]

SGPS/sgpsociais/models.py
from django.db import models
from django.contrib.auth.models import User

class Funcionario(models.Model):
    id = models.IntegerField(primary_key=True)
    nome = models.CharField(max_length=80)
    tipo_pessoa = models.TextField()  # This field type is a guess.
    nome_da_mae = models.CharField(max_length=80, blank=True, null=True)
    nome_do_pai = models.CharField(max_length=80, blank=True, null=True)
    estado_civil = models.CharField(max_length=15, blank=True, null=True)
    cpf = models.CharField(unique=True, max_length=11)
    situacao_moradia = models.CharField(max_length=20, blank=True, null=True)
    data_nascimento = models.DateTimeField()
    escola = models.CharField(max_length=30, blank=True, null=True)
    ano_escolar = models.CharField(max_length=15, blank=True, null=True)
    turno_escolar = models.TextField(blank=True, null=True)
    escolaridade = models.CharField(max_length=30, blank=True, null=True)
    bolsa_familia = models.BooleanField()

    class Meta:
        managed = False
        db_table = 'funcionario'


class Jovem(models.Model):
    id = models.IntegerField(primary_key=True)
    nome = models.CharField(max_length=80)
    data_nascimento = models.DateTimeField()
    sexo = models.CharField(max_length=2)
    nome_da_mae = models.CharField(max_length=80, blank=True, null=True)
    nome_do_pai = models.CharField(max_length=80, blank=True, null=True)
    naturalidade = models.CharField(max_length=20)
    cep = models.CharField(max_length=11,null=False)
    cidade = models.CharField(max_length=30)
    bairro = models.CharField(max_length=30)
    endereco = models.CharField(max_length=100)
    situacao_escolar = models.CharField(max_length=30)
    escola = models.CharField(max_length=30, blank=True, null=True)
    ano_escolar = models.IntegerField(blank=True, null=True)
    turno_escolar = models.IntegerField(blank=True, null=True)
    telefone = models.IntegerField(max_length=12, null=True)
    parentesco = models.CharField(max_length=20, null=True)
    diabetes = models.BooleanField(null=False)
    uso_med = models.BooleanField()
    desc_uso_med = models.CharField(max_length=30)
    dep_quim = models.BooleanField()
    desc_dep_quim = models.CharField(max_length=30)
    pressao_alta = models.BooleanField()
    sofre_doenca = models.BooleanField()
    alergia_med = models.BooleanField()
    med_controlado = models.BooleanField()
    desc_med_controlado = models.CharField(max_length=30)
    prioritario = models.BooleanField()
    obs = models.TextField(max_length=200)

    class Meta:
        managed = False
        db_table = 'pessoa'
    
    def __str__(self):
        return self.nome

class Crianca(models.Model):
    id = models.IntegerField(primary_key=True)
    nome = models.CharField(max_length=80)
    data_nascimento = models.DateTimeField()
    sexo = models.CharField(max_length=2)
    nome_da_mae = models.CharField(max_length=80, blank=True, null=True)
    nome_do_pai = models.CharField(max_length=80, blank=True, null=True)
    naturalidade = models.CharField(max_length=20)
    cep = models.CharField(max_length=11,null=False)
    cidade = models.CharField(max_length=30)
    bairro = models.CharField(max_length=30)
    endereco = models.CharField(max_length=100)
    situacao_escolar = models.CharField(max_length=30)
    escola = models.CharField(max_length=30, blank=True, null=True)
    ano_escolar = models.IntegerField(blank=True, null=True)
    turno_escolar = models.IntegerField(blank=True, null=True)
    telefone = models.IntegerField(max_length=12, null=True)
    parentesco = models.CharField(max_length=20, null=True)
    diabetes = models.BooleanField(null=False)
    uso_med = models.BooleanField()
    desc_uso_med = models.CharField(max_length=30)
    dep_quim = models.BooleanField()
    desc_dep_quim = models.CharField(max_length=30)
    pressao_alta = models.BooleanField()
    sofre_doenca = models.BooleanField()
    alergia_med = models.BooleanField()
    med_controlado = models.BooleanField()
    desc_med_controlado = models.CharField(max_length=30)
    prioritario = models.BooleanField()
    obs = models.TextField(max_length=200)

    class Meta:
        managed = False
        db_table = 'crianca'
    
    def __str__(self):
        return self.nome

class Usuario(User):
   # id = models.IntegerField(primary_key=True)
    #pessoa = models.ForeignKey(Pessoa, models.DO_NOTHING, blank=True, null=True)
    funcionario = models.ForeignKey(Funcionario, models.DO_NOTHING, blank=True, null=True)
   # nome_usuario = models.CharField(max_length=20)
   # senha = models.CharField(max_length=20)
    cpf = models.CharField(unique=True, max_length=11)
    nivel_permissao = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'usuario'

SGPS/sgpsociais/views.py
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import ModelForm
from .models import *



def logoff(request):
    logout(request)
    return redirect(settings.LOGIN_URL)

@login_required(login_url='/')
def home(request):
    return render(request, 'inicio.html')

'''
def logon(request, template_name="login.html"):
    next = request.GET.get('next', 'home/')
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(next)

        else:
            messages.error(request, 'Usuário ou senha incorretos.')
            return HttpResponseRedirect(settings.LOGIN_URL)
    elif
    return render(request, template_name, {'redirect_to': next})
'''

#Assim fica melhor pra autenticar o usuário
def logon(request, template_name="login.html"):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #loga o usuario
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('sgps:home')
    else:
        form = AuthenticationForm()
    return render(request, template_name, {'form': form})

@login_required(login_url='/')
def cadastro_jovem(request):
    return render(request, 'cadastro_jovem.html')

@login_required(login_url='/')
def cadastro_crianca(request):
    return render(request, 'cadastro_crianca.html')

@login_required(login_url='/')
def cadastro_idoso(request):
    return render(request, 'cadastro_idoso.html')

'''
def cadastro(request, template_name='cadastro.html'):
    form = PessoaForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('sgps:home')
    return render(request, template_name, {'form': form})
'''

@login_required(login_url='/')
def listar_jovem(request):
    return render(request, 'listagem_jovens.html')

@login_required(login_url='/')
def listar_crianca(request):
    return render(request, 'listagem_criancas.html')

@login_required(login_url='/')
def listar_idoso(request):
    return render(request, 'listagem_idosos.html')

@login_required(login_url='/')
def suporte(request):
    return render(request, 'suporte.html')

@login_required(login_url='/')
def preferencias(request):
    return render(request, 'preferencias.html')

SGPS/sgpsociais/templates/cadastro_crianca.html
{% extends 'menu.html' %}
{% load static %}


{% block title %}
Cadastrar Crianças - Sistema de Gerenciamento de Programas Sociais
{% endblock %}

{% block head %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js"></script>
<link rel="stylesheet" href="{% static 'js/jquery.maskedinput-1.1.4.pack.js' %}">
<script type="text/javascript">

  $(document).ready(() => {
    $("#cep").mask('99999-999');
    $("#telefone").mask('(99) 99999-9999');
  });

  function limpa_formulário_cep() {
    //Limpa valores do formulário de cep.
    document.getElementById('rua').value = ("");
    document.getElementById('bairro').value = ("");
    document.getElementById('cidade').value = ("");
  }

  function meu_callback(conteudo) {
    if (!("erro" in conteudo)) {
      //Atualiza os campos com os valores.
      document.getElementById('rua').value = (conteudo.logradouro);
      document.getElementById('bairro').value = (conteudo.bairro);
      document.getElementById('cidade').value = (conteudo.localidade);
    } //end if.
    else {
      //CEP não Encontrado.
      limpa_formulário_cep();
      alert("CEP não encontrado.");
    }
  }

  function pesquisacep(valor) {

    //Nova variável "cep" somente com dígitos.
    var cep = valor.replace(/\D/g, '');

    //Verifica se campo cep possui valor informado.
    if (cep != "") {

      //Expressão regular para validar o CEP.
      var validacep = /^[0-9]{8}$/;

      //Valida o formato do CEP.
      if (validacep.test(cep)) {

        //Preenche os campos com "..." enquanto consulta webservice.
        document.getElementById('rua').value = "...";
        document.getElementById('bairro').value = "...";
        document.getElementById('cidade').value = "...";

        //Cria um elemento javascript.
        var script = document.createElement('script');

        //Sincroniza com o callback.
        script.src = 'https://viacep.com.br/ws/' + cep + '/json/?callback=meu_callback';

        //Insere script no documento e carrega o conteúdo.
        document.body.appendChild(script);

      } //end if.
      else {
        //cep é inválido.
        limpa_formulário_cep();
        alert("Formato de CEP inválido.");
      }
    } //end if.
    else {
      //cep sem valor, limpa formulário.
      limpa_formulário_cep();
    }
  };

  window.onload = function () {
    document.getElementById('ifYes').style.display = 'none';
    document.getElementById('ifNo').style.display = 'none';
  }
  function yesnoCheck() {
    if (document.getElementById('usoMed').checked) {
      document.getElementById('simUsoMed').style.display = 'block';
    }
    if (document.getElementById('usoDepQuim').checked) {
      document.getElementById('simDepQuim').style.display = 'block';
    }
    if (document.getElementById('usoMedCtrl').checked) {
      document.getElementById('simUsoMedCtrl').style.display = 'block';
    }
  }


</script>

{% endblock %}

{% block content %}
<div class="titulo">
  <span>
    CADASTRAR CRIANÇAS
  </span>
</div>
<div class="sub-titulo">
  <span>
    Informações Pessoais
  </span>
  <hr style="background-color: lightgrey;">
</div>

<div class="contexto">
  <form>
    <!--class="was-validated"-->
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputNome">Nome</label>
        <input type="text" class="form-control" id="inputNome" placeholder="Nome Completo" >
        <div class="invalid-feedback">Este campo é obrigatório</div>
      </div>
      <div class="form-group col-md-3">
        <label for="inputDataNasc">Data de Nasc.</label>
        <input type="date" class="form-control" id="inputDataNasc">
      </div>
      <div class="form-group col-md-3">
        <label for="inputDataNasc">Sexo</label>
        <select class="custom-select" >
          <option value="">Informe o sexo</option>
          <option value="1">M</option>
          <option value="2">F</option>
        </select>
        <div class="invalid-feedback">Campo obrigatório</div>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="inputNomePai">Nome do Pai</label>
        <input type="text" class="form-control" id="inputNomePai" placeholder="Nome do Pai Completo" >
        <div class="invalid-feedback">Este campo é obrigatório</div>
      </div>
      <div class="form-group col-md-6">
        <label for="inputNomeMae">Nome da Mãe</label>
        <input type="text" class="form-control" id="inputNomeMae" placeholder="Nome da Mãe Completo">
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-4">
        <label for="inputNatu">Naturalidade</label>
        <input type="text" class="form-control" id="inputNatu" placeholder="Naturalidade" >
      </div>
      <div class="form-group col-md-2">
        <label for="cep">CEP</label>
        <input type="text" class="form-control" maxlength="9" id="cep" placeholder="CEP"
          onblur="pesquisacep(this.value);" >
      </div>
      <div class="form-group col-md-4">
        <label for="cidade">Cidade</label>
        <input type="text" class="form-control" id="cidade" placeholder="Cidade" >
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-4">
        <label for="bairro">Bairro</label>
        <input type="text" class="form-control" id="bairro" placeholder="Bairro" >
      </div>
      <div class="form-group col-md-8">
        <label for="rua">Endereço</label>
        <input type="text" class="form-control" id="rua" placeholder="Endereço" >
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-4">
        <label for="situacao_escolar">Situação Escolar</label>
        <input type="text" class="form-control" id="situacao_escolar" placeholder="Situação Escolar" >
      </div>
      <div class="form-group col-md-8">
        <label for="nome_escola">Nome da Escola</label>
        <input type="text" class="form-control" id="nome_escola" placeholder="Nome da Escola" >
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-3">
        <label for="inputSerie">Série</label>
        <select class="custom-select" >
          <option value="">Informe a série</option>
          <option value="1">1ª</option>
          <option value="2">2ª</option>
          <option value="3">3ª</option>
          <option value="4">4ª</option>
          <option value="5">5ª</option>
          <option value="6">6ª</option>
          <option value="7">7ª</option>
          <option value="8">8ª</option>
          <option value="9">9ª</option>
          <option value="10">1º Ano</option>
          <option value="11">2° Ano</option>
          <option value="12">3º Ano</option>
        </select>
        <div class="invalid-feedback">Campo obrigatório</div>
      </div>
      <div class="form-group col-md-3">
        <label for="inputTurno">Turno</label>
        <select class="custom-select" >
          <option value="">Informe o turno</option>
          <option value="1">Manhã</option>
          <option value="2">Tarde</option>
          <option value="3">Noite</option>
        </select>
        <div class="invalid-feedback">Campo obrigatório</div>
      </div>

      <div class="form-group col-md-4">
        <label for="telefone">Telefone</label>
        <input type="text" class="form-control" id="telefone" placeholder="Telefone" >
      </div>
      <div class="form-group col-md-3">
        <label for="parentesco">Parentesco</label>
        <input type="text" class="form-control" id="parentesco" placeholder="Parentesco" >
      </div>
    </div>
</div>

<div class="sub-titulo">
  <span>
    Condições de Saúde
  </span>
  <hr style="background-color: lightgrey;">
</div>

<div class="contexto">
  <!--class="was-validated"-->
  <div class="form-row">
    <div class="form-group col-md-2">
      <input type="checkbox" id="diabetico" />
      <label>Diabético</label>
    </div>

    <div class="form-group col-md-4">
      <input type="checkbox" onclick="javascript:yesnoCheck();" name="yesno" id="usoMed" />
      <label>Faz uso contínuo de medicamento?</label>
      <div id="simUsoMed" style="display:none">
        <input type="text" class="form-control" id="usomedicamento" placeholder="Uso de">
      </div>
    </div>

    <div class="form-group col-md-5">
      <input type="checkbox" onclick="javascript:yesnoCheck();" name="yesno" id="usoDepQuim" />
      <label>Alguém é dependente químico?</label>
      <div id="simDepQuim" style="display:none">
        <input type="text" class="form-control" id="dependentequim" placeholder="Uso de">
      </div>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-3">
      <input type="checkbox" id="pressaoalta" />
      <label>Tem pressão alta?</label>
    </div>
    <div class="form-group col-md-3">
      <input type="checkbox" id="sofredoenca" />
      <label>Sofre de alguma doença?</label>
    </div>
    <div class="form-group col-md-4">
      <input type="checkbox" id="alergia" />
      <label>Tem alergia a algum medicamento?</label>
    </div>
  </div>

  <div class="form-row">

    <div class="form-group col-md-4">
      <input type="checkbox" onclick="javascript:yesnoCheck();" name="yesno" id="usoMedCtrl" />
      <label>Toma algum remédio Controlado?</label>
      <div id="simUsoMedCtrl" style="display:none">
        <input type="text" class="form-control" id="usomedicamentoctrl" placeholder="Uso de">
      </div>
    </div>
    <div class="form-group col-md-4">
      <input type="checkbox" id="prioritario" />
      <label>Prioritátio?</label>
    </div>
  </div>

  <div class="form-row">

    <div class="form-group col-md-4">
      <label for="obs">Observações</label>
      <textarea id="obs" placeholder="Observações"></textarea>
    </div>
  </div>


  <button type="submit" class="btn btn-primary btn-block btn-large">Salvar</button>
</div>


</form>

{% endblock %}

SGPS/sgpsociais/templates/inicio.html
{% extends 'menu.html' %}

{% block title %}
Início - Gerenciamento de Programas Sociais
{% endblock %}

{% block content %}
                <div class="titulo">
                    <span>
                        BEM VINDO
                    </span>
                </div>

                <div class="contexto">
                    <p>
                        Manual de Utilização:
                        <br><br>
                        • Utilize "Cadastro" para realizar o cadastramento de uma pessoa, que participe de programas sociais.
                        <br>
                        • Utilize "Listar Cadastros" para listar as pessoas que participam dos programas sociais.
                        <br>
                        • Utilize "Suporte" para reportar algum poblema ou entrar em contato com a equipe de manutenção.
                    </p>
                </div>
            </div>
{% endblock %}

SGPS/sgpsociais/templates/listagem_criancas.html
{% extends 'menu.html' %}

{% block title %}
 Listagem Crianças - Sistema de Gerenciamento de Programas Sociais
{% endblock %}


{% block content %}
<div class="titulo">
        <span>
            LISTA DE CRIANÇAS
        </span>
    </div>

    <div class="contexto">

        <div class="pesquisa">
            <div class="pesquisa-conteudo">
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Pesquisar" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
                 </form>
            </div>
        </div>    
    {% for crianca in lista %}
        <div class="box">
            <div class="conteudo-box">
                <span class="avatar current"><img src="http://sosfisica.com.br/moodle/theme/image.php/boost/core/1553449005/u/f2" class="userpicture defaultuserpic" width="50 " height="50" role="presentation
            " aria-hidden="true"></span>

                <div>
                    <span class="jss645">Nome</span>
                    <p class="jss647">{{ crianca.nome }}</p>
                </div>

                <div>
                    <span class="jss646">Data de nascimento</span>
                    <p class="jss647">{{crianca.data_nascimento}}</p>
                </div>

                <div>
                    <span class="jss648">Sexo</span>
                    <p class="jss647">{{crianca.sexo}}</p>
                </div>

                <div>
                    <span class="jss648">Naturalidade</span>
                    <p class="jss647">{{crianca.naturalidade}}</p>
                </div>

                <a href="#">
                <span class="bot-box">VER MAIS</span>
                </a>
            </div>
        </div>
    {% endfor %}

        <!--<nav aria-label="Page navigation example">
          <ul class="pagination">
            <li class="page-item">
              <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
              <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          </ul>
        </nav> -->


    </div>
</div>

{% endblock %}

SGPS/sgpsociais/templates/menu.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/principal.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600,700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/dd64c0f8b3.js"></script>
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'imgs/favicon.png' %}">
    <title> 
        {% block title %}

        {% endblock %}
    </title>

    {% block head %}

    {% endblock %}

</head>

<body>
    <nav class="navbar navbar-light">
        <div id="barra">
            <div class="logo-site">
                <a href="inicio.html"><img src="{% static 'imgs/logo.png' %}" height="46"></a>
            </div>
            <div class="btn-group">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true aria-expanded=" false ">
                    <span class="avatars "><span class="avatar current"><img src="{{STATIC_URL}}http://sosfisica.com.br/moodle/theme/image.php/boost/core/1553449005/u/f2" class="userpicture defaultuserpic" width="35 " height="35 " role="presentation
                    " aria-hidden="true"></span></span>
                   {{user.username|slugify}}
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <button class="dropdown-item" type="button">
                        <a href="{% url 'sgps:preferencias' %}">
                            <span class="media-left">
                                <i class="icon fa fa-wrench fa-fw"></i>
                            </span> 
                            Preferências
                        </a>
                    </button>
                    <form method="post" action="{% url 'sgps:logoff' %}">
                        {% csrf_token %}
                   <button class="dropdown-item" type="submit">
                        <a >
                            <span class="media-left">
                                <i class="fas fa-sign-out-alt"></i>
                            </span> 
                            Sair
                        </a>
                    </button>
                    </form>
                </div>
            </div>
        </div>
    </nav>




    <div id="main">

        <div id="group-menu">
                <a class="item-group-menu" href="{% url 'sgps:home' %}">
                    <span class="icon-menu">
                        <i class="fas fa-home"></i>
                    </span>
                    <span>Página inicial</span>
                </a>

                <a class="item-group-menu"  data-toggle="collapse" data-target="#cadastro" aria-controls="cadastro" aria-expanded="true" aria-label="Toggle navigation">
                    <span class="icon-menu">
                        <i class="fas fa-folder-plus"></i>
                    </span>
                    <span>Cadastrar</span>
                </a>

                <div class="collapse" id="cadastro" style=" ">
                        <a class="item-group-menu-2" href="{% url 'sgps:cadastro_crianca' %}">
                            <span class="icon-menu">
                                    <i class="fas fa-child"></i>
                                 </span>
                            <span>Crianças</span>
                        </a>
                        <a class="item-group-menu-2" href="{% url 'sgps:cadastro_jovem' %}">
                            <span class="icon-menu">
                                    <i class="fas fa-walking"></i>
                                 </span>
                            <span>Jovens</span>
                        </a>
                        <a class="item-group-menu-2" href="{% url 'sgps:cadastro_idoso' %}">
                            <span class="icon-menu">
                                    <i class="fas fa-blind"></i>
                                 </span>
                            <span>Idosos</span>
                        </a>
                </div>

                <a class="item-group-menu" href="#" data-toggle="collapse" data-target="#sobreNos" aria-controls="sobreNos" aria-expanded="true" aria-label="Toggle navigation">
                    <span class="icon-menu">
                        <i class="fas fa-list-ul"></i>
                    </span>
                    <span>Listar Cadastros</span>
                </a>

                <div class="collapse" id="sobreNos" style=" ">
                        <a class="item-group-menu-2" href="{% url 'sgps:listar_crianca' %}">
                            <span class="icon-menu">
                                    <i class="fas fa-child"></i>
                                 </span>
                            <span>Crianças</span>
                        </a>
                        <a class="item-group-menu-2" href="{% url 'sgps:listar_jovem' %}">
                            <span class="icon-menu">
                                    <i class="fas fa-walking"></i>
                                 </span>
                            <span>Jovens</span>
                        </a>
                        <a class="item-group-menu-2" href="{% url 'sgps:listar_idoso' %}">
                            <span class="icon-menu">
                                    <i class="fas fa-blind"></i>
                                 </span>
                            <span>Idosos</span>
                        </a>
                </div>


                <a class="item-group-menu" href="{% url 'sgps:suporte' %}">
                    <span class="icon-menu"> 
                        <i class="fas fa-address-book"></i>
                    </span>
                    <span>Suporte</span>
                </a>

        </div>

        


        <div id="lateral-direita">
            <div class="conteudo">
              {% block content %}

              {% endblock %}
         </div>
    </div>


    <script rel="stylesheet " src="{% static 'js/teste.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

SGPS/sgpsociais/templates/suporte.html
{% extends 'menu.html' %}

{% block title %}
   Suporte - Sistema de Gerenciamento de Programas Sociais
{% endblock %}

{% block content %}
<div class="titulo">
    <span>
        SUPORTE
    </span>
</div>

<div class="contexto">
    <p>
        Manual de Utilização:
        <br><br>
        • Utilize "Cadastro" para realizar o cadastramento de uma pessoa, que participe de programas sociais.
        <br>
        • Utilize "Listar Cadastros" para listar as pessoas que participam dos programas sociais.
        <br>
        • Utilize "Suporte" para reportar algum poblema ou entrar em contato com a equipe de manutenção.
    </p>
</div>
</div>
</div>
</div>

{% endblock %}